/**
 * Trophy Media URLs from R2
 *
 * Maps trophy card names to their R2-hosted image and video URLs.
 * Generated by scripts/generate-trophy-r2-json.ts
 */

import trophyMediaJson from './trophy-media.json'

export interface TrophyMedia {
  image: string
  video?: {
    thumbnail: string
    detail: string
  }
}

export const TROPHY_MEDIA: Record<string, TrophyMedia> = trophyMediaJson

/**
 * Look up media for a trophy by its image file name (without path/extension).
 * Examples:
 *   - "Sableye" → matches trophy-cards/images/Sableye.webp
 *   - "rayquaza-metal_md" → won't match; use "Rayquaza"
 */
export function getTrophyMedia(name: string): TrophyMedia | undefined {
  // Try exact match first
  if (TROPHY_MEDIA[name]) return TROPHY_MEDIA[name]

  // Try case-insensitive match
  const lower = name.toLowerCase()
  for (const [key, media] of Object.entries(TROPHY_MEDIA)) {
    if (key.toLowerCase() === lower) return media
  }

  return undefined
}

/**
 * Map from legacy local image paths to R2 media keys.
 * Update this as you rename/reorganize trophies.
 */
export const LEGACY_IMAGE_MAP: Record<string, string> = {
  // Tier trophies
  '/cards/rayquaza-metal_md.webp': 'Rayquaza',
  '/cards/Tyranitar-metal_md.webp': 'Tyranitar',

  // Achievement trophies
  '/cards/trophies/Sableye.webp': 'Sableye',
  '/cards/trophies/Bulbasaur.png': 'Bulbasaur',
  '/cards/trophies/Venusaur.png': 'Venusaur',
  '/cards/trophies/Blastoise.png': 'Blastoise',
  '/cards/trophies/Espeon.webp': 'Espeon',
  '/cards/trophies/Groudon.png': 'Groudon',
  '/cards/trophies/Kyogre.png': 'Kyogre',
  '/cards/trophies/Metagross.png': 'Metagross',
  '/cards/trophies/Mewtwo.png': 'Mewtwo',
  '/cards/trophies/Arceus2.png': 'Arceus2',
}

/**
 * Resolve a legacy image path to its R2 URL.
 */
export function resolveTrophyImage(legacyPath: string): string {
  const key = LEGACY_IMAGE_MAP[legacyPath]
  if (key) {
    const media = getTrophyMedia(key)
    if (media) return media.image
  }
  return legacyPath
}
